# Generated by Django 5.1.5 on 2026-08-17 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('logo', models.ImageField(blank=True, upload_to='org_logos/')),
                ('description', models.TextField(blank=True)),
                ('website', models.URLField(blank=True)),
                ('employee_count', models.PositiveIntegerField(blank=True, null=True)),
                ('funding_stage', models.CharField(blank=True, max_length=50)),
                ('industry', models.CharField(blank=True, max_length=80)),
                ('is_verified', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
