# Generated by Django 5.1.5 on 2026-08-17 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='team_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='team_size',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
