# Generated by Django 5.1.5 on 2026-08-17 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('jobs', '0001_initial'),
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='resumes/')),
                ('filename', models.CharField(blank=True, max_length=255)),
                ('is_primary', models.BooleanField(default=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resumes', to='accounts.applicantprofile')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeAnalysis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_match_pct', models.PositiveSmallIntegerField()),
                ('technical_skills_match_pct', models.PositiveSmallIntegerField()),
                ('experience_relevancy_pct', models.PositiveSmallIntegerField()),
                ('keyword_density_pct', models.PositiveSmallIntegerField()),
                ('ai_insight', models.TextField(blank=True)),
                ('similar_profiles_count', models.PositiveIntegerField(default=0)),
                ('processing_time_seconds', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('engine_version', models.CharField(blank=True, max_length=20)),
                ('analyzed_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_analyses', to='jobs.job')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analyses', to='resumes.resume')),
            ],
            options={
                'verbose_name_plural': 'resume analyses',
                'ordering': ['-analyzed_at'],
            },
        ),
        migrations.CreateModel(
            name='OptimizationSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('impact', models.CharField(choices=[('high', 'High impact'), ('medium', 'Medium impact'), ('low', 'Low impact')], max_length=10)),
                ('is_addressed', models.BooleanField(default=False)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='resumes.resumeanalysis')),
            ],
        ),
        migrations.CreateModel(
            name='ResumeSkillMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('matched', 'Matched'), ('partial', 'Partially matched'), ('missing', 'Missing')], max_length=10)),
                ('analysis', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_matches', to='resumes.resumeanalysis')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_matches', to='taxonomy.skill')),
            ],
            options={
                'unique_together': {('analysis', 'skill')},
            },
        ),
    ]
