# Generated by Django 5.1.5 on 2026-09-06 07:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resume',
            name='source',
            field=models.CharField(choices=[('uploaded', 'Uploaded'), ('generated', 'Generated from profile')], default='uploaded', max_length=10),
        ),
        migrations.AlterField(
            model_name='resume',
            name='file',
            field=models.FileField(blank=True, upload_to='resumes/'),
        ),
    ]
